spring:
  application:
    name: simulator-service
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:${{ rabbitmq.RAILWAY_PRIVATE_DOMAIN }}}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USER:guest}
    password: ${SPRING_RABBITMQ_PASS:guest}

server:
  port: 8085

simulator:
  enabled: true
  tick-interval-ms: 1000
  locomotives:
    - id: KZ8A-0042
      type: KZ8A
      route: ASTANA-ALMATY
    - id: TE33A-0187
      type: TE33A
      route: ASTANA-KARAGANDA
  anomaly:
    probability: 0.02
    duration-seconds: 60

ingestion:
  service:
    url: ${INGESTION_URL:http://localhost:8081}